### ISSUE TITLE
Update README with clearer instructions/version constraints

### ISSUE THREAD

**Issue by rodriguezsergio** [airbnb/kafka-statsd-metrics2#1]
Any chance the README can be updated with what versions of java and kafka this plugin has been tested against? Or with clearer instructions if I happen to missing something.

I'm running on Ubuntu 12.04 with openjdk 7 and kafka 2.9.2-0.8.1.1, but kafka will fail to initialize when I add `kafka.metrics.reporters=com.airbnb.kafka.KafkaStatsdMetricsReporter` to config/server.properties. The kafka-gc.log doesn't help me at all, so I'm a complete loss as to what I am doing wrong.

I'm doing the following, but it's not working out.

```
git clone $REPO
cd kafka-statsd-metrics2
./gradlew shadowJar
mv build/lib/$JAR /opt/kafka/libs
chown kafka:kafka /opt/kafka/libs/$JAR
vi /opt/kafka/config/server.properties
sudo service kafka start
```

**Comment by alexism** [comment]
Hi @srodrig0209 

first of I'm sorry for not noticing your issue earlier. My Github notifications were off.

Regarding your problem, the gc log won't be helpful. Instead you should look in the kafka broker log. This would typically be the standard output or in a log file under `kafka_2.9.2-0.8.1.1/logs/`.

When the reporter starts, it will log an `INFO` message saying `"Kafka Statsd metrics reporter is enabled"`. Any exception should be reported as well.

More details at https://github.com/airbnb/kafka-statsd-metrics2/blob/master/README.md#how-to-test-your-configuration

**Comment by rodriguezsergio** [comment]
Yep, I've since found out that it's the broker log that I need to look at. Thanks.
