### ISSUE TITLE
Unable to find class upon starting kafka server

### ISSUE THREAD

**Issue by neko1991** [airbnb/kafka-statsd-metrics2#14]
Hi,
I downloaded file kafka-statsd-metrics2-0.4.1.jar and placed it in directory kafka_2.11-0.9.0.0/libs, edited server.properties file to include kafka.metrics.reporters=com.airbnb.kafka.KafkaStatsdMetricsReporter and I get following problem upon stariting kafka broker:
java.lang.ClassNotFoundException: com.timgroup.statsd.StatsDClientException

I thought that libs directory is authomatically scanned for all files upon starting server. What am I missing?
Thanks for help in advance.

**Comment by neko1991** [comment]
Now I see that this class doesn't exist in jar package, even when I build it localy I got the same archive. How could this happen?

**Comment by neko1991** [comment]
Just in case someone else come into this problem, problem was that lightweitght statsd library client is used within this project, so its jar must be included in libs directory too.

**Comment by evbo** [comment]
This is the jar according to @neko1991 : https://github.com/tim-group/java-statsd-client

However, this approach will not ensure other dependencies are correctly versioned. You should instead download the source, update the build.gradle to satisfy your dependency versions (e.g. for kafka) and build the shadow (fat) jar. Then you wont need to download that extra jar.

**Comment by rjkernick** [comment]
With kafka version 0.10.2.x. The reporter has to implement KafkaMetricsReporter and KafkaMetricsReporterMBean. This is why it no longer works.

**Comment by izm1chael** [comment]
https://github.com/airbnb/kafka-statsd-metrics2/issues/14#issuecomment-162931496

What folder did you drop the missing dep into, was it in its own folder in `/var/lib/apache-druid/extensions`


Having the same issue, however upon adding this missing dep into a folder of the same name in the exstentions folder same result
