### ISSUE TITLE
Does this project work with kafka 0.9?

### ISSUE THREAD

**Issue by neko1991** [airbnb/kafka-statsd-metrics2#15]
Hi, I am unable to get kafka 0.9 metrics to statsd, I am using this configuration in broker:
# Statsd
# declare the reporter

kafka.metrics.reporters=com.airbnb.kafka.KafkaStatsdMetricsReporter
# enable the reporter, (false)

external.kafka.statsd.reporter.enabled=true
# the host of the StatsD server (localhost)

external.kafka.statsd.host=127.0.0.1
# the port of the StatsD server (8125)

external.kafka.statsd.port=8125
# enable the support of statsd tag extension, e.g. datadog statsd (true)

external.kafka.statsd.tag.enabled=false
# a prefix for all metrics names (empty)

external.kafka.statsd.metrics.prefix=kafka

**Comment by neko1991** [comment]
I got this in log:
INFO Reporter is enabled and starting... (com.airbnb.metrics.StatsDReporter)
And when from jconsole try to start reporter I get message in log:
WARN Reporter is already running (com.airbnb.metrics.StatsDReporter)

**Comment by alexism** [comment]
Hi @neko1991 

I haven't tried the reporter with kafka 0.9. 
- for the new clients implementations, considering a [custom metrics](https://github.com/apache/kafka/tree/trunk/clients/src/main/java/org/apache/kafka/common/metrics) framework is used, I'm pretty sure `kafka-statsd-metrics2` won't work unfortunately. 
- for brokers, the yammer metrics framework seems to still be used. So `kafka-statsd-metrics2` should work. However, I would still recommend searching the release notes/Jira for metric changes. Testing highly recommended obviously.

Please share your findings with us!

Hope it helps.

**Comment by neko1991** [comment]
Hi, thanks for help, it helped a lot. 
You were absolutelly right about brokers, it works. For kafka client I am not sure, haven't tried it, but since good API for clients is available now I am not sure it is needed at all.
I am investigating kafka, and problem was with configuration:
I am using kafka virtual mashine and my statsd was on my main mashine so probably due proxy configuration or ip resoultion metrics weren't coming to statsd. After I installed statsd on virtual and in kafka corrected statsd IP to localhost it worked ok.

Thank you very much again.
