### ISSUE TITLE
Not able to see all metrics in 0.8.2

### ISSUE THREAD

**Issue by mydiemho** [airbnb/kafka-statsd-metrics2#8]
I am using Kafka 0.8.2 but I am not able to see all metrics listed in "List of metrics for Kafka 0.8.2".

For example, I can see "kafka.server.BrokerTopicMetrics.MessagesInPerSec_all" but not "kafka.server.BrokerTopicMetrics.MessagesInPerSec".

Java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

**Comment by alexism** [comment]
are you sending the metrics to a standard Statsd server?
I suspect it's because your statsd server does not support tags. 

See https://github.com/airbnb/kafka-statsd-metrics2#040

**Comment by mydiemho** [comment]
Thanks, that clears up the confusion.
